{{ if .Values.api.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
spec:
  rules:
  {{- range .Values.api.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
        - path: /
          backend:
            service:
              name: {{ $.Release.Name }}-api-service
              port:
                number: 80
          pathType: Prefix
  {{- end }}
{{ end }}