apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongodb-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mongodb
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mongodb
    spec:
      containers:
        - image: mongo:{{ .Values.mongodb.tag }}
          name:  mongodb
          ports:
            - containerPort: 27017
          resources: {}
          env:
            - name:  MONGO_INITDB_ROOT_USERNAME
              value:  {{ .Values.mongodb.user }}
            - name:  MONGO_INITDB_ROOT_PASSWORD
              value:  {{ .Values.mongodb.password }}
